GestionRestaurant/Models/Panier.cs
using System;
using System.Collections.Generic;
using System.Diagnostics.Contracts;
using System.Linq;
using System.Threading.Tasks;

namespace GestionRestaurant.Models
{
    public class Panier : IPanier
    {
        public Panier()
        {
            Items = new List<ItemPanier>();
        }

        public virtual ICollection<ItemPanier> Items { get; set; }

        public double Total => Items.Sum(item => item.Item.Prix * item.Quantité);


        public virtual void Vider()
        {
            Items.Clear();
        }

        public void AjouterItem(ItemMenu item, int quantité)
        {
            Contract.Assert(item != null);

            var itemExistant = Items.FirstOrDefault(_ => _.Item.Id == item.Id);
            if (itemExistant == null)
            {
                itemExistant = new ItemPanier() { Item = item, Quantité = 0 };
                Items.Add(itemExistant);
            }

            AjusterQuantité(item.Id, itemExistant.Quantité + quantité);
        }

        public virtual void AjusterQuantité(Guid id, int quantité)
        {
            var item = Items.FirstOrDefault(_ => _.Item.Id == id);
            if (item != null)
            {
                item.Quantité = Math.Max(0, quantité);
                if (item.Quantité == 0)
                {
                    Items.Remove(item);
                }
            }
        }

    }
}

GestionRestaurant/Pages/Paniers/Ajouter.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace GestionRestaurant.Pages.Paniers
{
    public class AjouterModel : PageModel
    {
        private Models.ContexteRestaurant Restaurant { get; set; }
        private Models.IPanier Panier { get; set; }

        public AjouterModel(Models.ContexteRestaurant restaurant,  Models.IPanier panier)
        {
            Restaurant = restaurant;
            Panier = panier;
        }


        [BindProperty(Name = "Item")]
        public Guid ItemId { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            var item = await Restaurant.Menu.FindAsync(ItemId);
            if (item == null)
            {
                return BadRequest();
            }

            Panier.AjouterItem(item, 1);                
            return Redirect("~/Paniers");
        }

    }
}

GestionRestaurant/Pages/Paniers/Commander.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using GestionRestaurant.Models;
using GestionRestaurant.Session;

namespace GestionRestaurant.Pages.Paniers
{
    public class CommanderModel : PageModel
    {
        private Models.ContexteRestaurant Restaurant { get; set; }
        private Models.IPanier Panier { get; set; }


        public CommanderModel(GestionRestaurant.Models.ContexteRestaurant restaurant, Models.IPanier panier)
        {
            Restaurant = restaurant;
            Panier = panier;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            await AssignerCommande();

            return Page();
        }

        public Commande Commande { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await AssignerCommande();

            foreach (var item in Commande.Items)
            {

            }

            Restaurant.Commandes.Add(Commande);
            await Restaurant.SaveChangesAsync();

            Panier.Vider();

            return RedirectToPage("/Commandes/Details", new { Id = Commande.Id });
        }

        private async Task AssignerCommande()
        {
            Commande = new Commande();
            Commande.État = ÉtatCommande.EnPréparation;
            Commande.MomentCommandé = DateTime.Now;
            Commande.MomentLivraisonEstimé = DateTime.Now.AddMinutes(30);
            Commande.Client = await Restaurant.Clients.FindAsync(HttpContext.Session.GetIdClient());
            Commande.Items = Panier.Items.Select(_ => new ItemCommande(_)).ToList();
            foreach (var item in Commande.Items)
            {
                item.Item = await Restaurant.Menu.FindAsync(item.Item.Id);
            }

        }
    }
}

GestionRestaurant/Pages/Paniers/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GestionRestaurant.Session;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Stripe;

namespace GestionRestaurant.Pages.Paniers

{
    public class IndexModel : PageModel
    {
        private Models.ContexteRestaurant Restaurant { get; set; }
        public Models.IPanier Panier { get; set; }

        public IndexModel(Models.ContexteRestaurant restaurant, Models.IPanier panier)
        {
            Restaurant = restaurant;
            Panier = panier;
        }

        [BindProperty]
        public Dictionary<string, int> Items { get; set; }


        public void OnGet()
        {

        }

        public IActionResult OnPost()
        {
            AjusterPanier();
            return Page();
        }

        public async Task<IActionResult> OnPostSupprimer(Guid id)
        {
            var item = await Restaurant.Menu.FindAsync(id);
            if (item == null)
            {
                return BadRequest();
            }

            AjusterPanier(); // Ajuste le panier avec le contenu du post, puis supprime l'élément demandé
            Panier.AjusterQuantité(item.Id, 0);
            return Page();
        }

        public IActionResult OnPostCommander()
        {
            AjusterPanier();

            if (HttpContext.Session.GetIdClient() == null)
            {
                return Redirect("~/Clients/Creer");
            }
            else
            {
                return Redirect("~/Paniers/Commander");
            }
        }
        public IActionResult Charge(string stripeToken)
        {

            // Set your secret key: remember to change this to your live secret key in production
            // See your keys here: https://dashboard.stripe.com/account/apikeys

            StripeConfiguration.ApiKey = "sk_test_kaFI3ObL3yYABrYN12dlnACT00JgXIxenk";

            // Token is created using Checkout or Elements!
            // Get the payment token submitted by the form:
            //var token = model.Token; // Using ASP.NET MVC

            var options = new ChargeCreateOptions
            {
                Amount = 999,
                Currency = "cad",
                Description = "Exemple charge",
                Source = stripeToken,
            };
            var service = new ChargeService();
            Charge charge = service.Create(options);

            if (charge.Paid)
            {
                return Redirect("~/Paniers/Commander");
            }
            //Request.Form
            return Page();
        }
        protected void AjusterPanier()
        {
            foreach (var item in Items)
            {
                if (Guid.TryParse(item.Key, out var guid))
                {
                    Panier.AjusterQuantité(guid, item.Value);
                }
            }
        }
    }
}

GestionRestaurant/Pages/Paniers/Ajouter.cshtml
@page
@model GestionRestaurant.Pages.Paniers.AjouterModel
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

GestionRestaurant/Pages/Paniers/Commander.cshtml
@page
@model GestionRestaurant.Pages.Paniers.CommanderModel

@{
    ViewData["Title"] = "Commander";
    ViewData["parallax-src"] = "/images/blog_3.jpg";
    ViewData["home-title"] = "Validation de la commande";
}


<div class="row">
    <div class="col">
        <h3>@Html.DisplayNameFor(model => model.Commande.Client.Nom)</h3>
        @Html.DisplayFor(model => model.Commande.Client.Nom)
        <h3>@Html.DisplayNameFor(model => model.Commande.Client.Adresse)</h3>
        @Html.DisplayFor(model => model.Commande.Client.Adresse)
        <h3>@Html.DisplayNameFor(model => model.Commande.Client.Téléphone)</h3>
        @Html.DisplayFor(model => model.Commande.Client.Téléphone)
    </div>
</div>
<hr />
<h2>Commande</h2>
<div class="row">
    <table class="table col-12">
        <thead>
            <tr>
                <th scope="col">Item</th>
                <th scope="col" class="text-right">@Html.DisplayNameFor(model => model.Commande.Items.First().Quantité)</th>
                <th scope="col" class="text-right">@Html.DisplayNameFor(model => model.Commande.Items.First().PrixUnitaire)</th>
                <th scope="col" class="text-right">Total</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Commande.Items)
            {
                <tr>
                    <th scope="row">@item.Item.Nom</th>
                    <td class="text-right">@item.Quantité</td>
                    <td class="text-right">@item.PrixUnitaire $</td>
                    <td class="text-right">@item.PrixTotal $</td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td class="text-right">@Model.Commande.PrixTotal $</td>
            </tr>

        </tfoot>
    </table>

</div>

<form method="post">
    <div class="row">
        <div class="ml-auto">
            <button class="btn btn-dark">Confirmer</button>
        </div>
    </div>
</form>

<div>
    <a asp-page="/Index">Continuer à magasiner</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

GestionRestaurant/Pages/Paniers/Index.cshtml
@page
@model GestionRestaurant.Pages.Paniers.IndexModel
@{
    ViewData["Title"] = "Panier";
    ViewData["parallax-src"] = "/images/home.jpg";
    ViewData["home-title"] = "Commande";
}

@section Styles {
    <link rel="stylesheet" href="~/css/panier.css" />
}


@if (!Model.Panier.Items.Any())
{
    <h2>Votre panier est vide.</h2>
    <a asp-page="../Index" class="btn">Retour à l'accueil</a>
}
else
{
    <a asp-page="../Index" class="btn">Ajouter d'autre items</a>
    <form method="post">
        <div class="row">
            @foreach (var item in Model.Panier.Items)
            {
                <div class="col-sm-4">
                    <partial name="_CommandeItem" model="@item" />
                </div>
            }
        </div>
        <div class="row">
            <h4 class="ml-auto">Total: @Model.Panier.Total</h4>
        </div>
    </form>
    <form asp-page-handler="Commander" method="post" id="payment-form">
        <div class="form-row">
            <label for="card-element">
                Credit or debit card
            </label>
            <div id="card-element" class="col-12">
                <!-- A Stripe Element will be inserted here. -->
            </div>

            <!-- Used to display Element errors. -->
            <div id="card-errors" role="alert"></div>
        </div>

        <button class="btn btn-info">Payer</button>
    </form>
    @section Stripe {
        <script src="https://js.stripe.com/v3/"></script>

        <script>
            // Create a Stripe client.
            var stripe = Stripe('pk_test_TYooMQauvdEDq54NiTphI7jx');

            // Create an instance of Elements.
            var elements = stripe.elements();

            // Custom styling can be passed to options when creating an Element.
            // (Note that this demo uses a wider set of styles than the guide below.)
            var style = {
                base: {
                    color: '#32325d',
                    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                    fontSmoothing: 'antialiased',
                    fontSize: '16px',
                    '::placeholder': {
                        color: '#aab7c4'
                    }
                },
                invalid: {
                    color: '#fa755a',
                    iconColor: '#fa755a'
                }
            };

            // Create an instance of the card Element.
            var card = elements.create('card', { style: style });

            // Add an instance of the card Element into the `card-element` <div>.
            card.mount('#card-element');

            // Handle real-time validation errors from the card Element.
            card.addEventListener('change', function (event) {
                var displayError = document.getElementById('card-errors');
                if (event.error) {
                    displayError.textContent = event.error.message;
                } else {
                    displayError.textContent = '';
                }
            });

            // Handle form submission.
            var form = document.getElementById('payment-form');
            form.addEventListener('submit', function (event) {
                event.preventDefault();

                stripe.createToken(card).then(function (result) {
                    if (result.error) {
                        // Inform the user if there was an error.
                        var errorElement = document.getElementById('card-errors');
                        errorElement.textContent = result.error.message;
                    } else {
                        // Send the token to your server.
                        stripeTokenHandler(result.token);
                    }
                });
            });

            // Submit the form with the token ID.
            function stripeTokenHandler(token) {
                // Insert the token ID into the form so it gets submitted to the server
                var form = document.getElementById('payment-form');
                var hiddenInput = document.createElement('input');
                hiddenInput.setAttribute('type', 'hidden');
                hiddenInput.setAttribute('name', 'stripeToken');
                hiddenInput.setAttribute('value', token.id);
                form.appendChild(hiddenInput);

                // Submit the form
                form.submit();
            }
        </script>
    }
}